-- ═══════════════════════════════════════════════════════════════════════════
-- 📋 KPI Standard 2026 — ทะเบียน KPI มาตรฐานรายหน่วยงาน (Main project)
--    ewhdfqwfwofivojtsizn · ชื่อในจอ Supabase = "MAIN"              2026-09-21
--
-- ที่มา: `KPI Guideline 2026 (as of 29.01.2026)` หน้า 7-18 — ส่วนที่ 2 "KPI Standard 2026"
--   จัดทำโดย Ms. Sasiwimol Aryupantewan (Internal Audit & Analysis Manager)
--   👉 รายละเอียด + ตารางเทียบ: docs/OBEYA-KPI-SOURCES.md §15
--
-- ทำไมต้องมีตารางนี้แยกจาก `kpi_catalog`:
--   `kpi_catalog` = "ชื่อ KPI ที่ระบบนี้ใช้" (ผู้ใช้แก้ได้ · `kpi_definitions.catalog_id` ชี้มา)
--   ตารางนี้    = "เอกสารอ้างอิงของกลุ่ม รายปี" อ่านอย่างเดียวในทางปฏิบัติ · 1 KPI โผล่ได้หลายหน่วยงาน
--   ⚠️ ถ้ายัดรวมกัน: `TS Academy training` มีครบทั้ง 24 หน่วยงาน ⇒ ทะเบียนชื่อจะมี 24 แถวซ้ำ
--      และ `catalog_id` จะกำกวมทันที — จึงแยกตาราง แล้วผูกกันด้วย `catalog_id` (nullable)
--
-- 🔴 กติกาการเลือกที่เอกสารเขียนไว้ตรงๆ:
--      `fixed`  = KPI บังคับของหน่วยงานนั้น ต้องมี
--      `choice` = เลือกได้
--      null     = แถวหัวข้อแม่ที่ไม่มีคะแนนเอง (เช่น "Activity" ที่มีลูกเป็น QCC / Engineering Day)
--   แต่ละหน่วยงาน = หยิบ `fixed` ทั้งหมด + ติ๊ก `choice` เท่าที่ต้องการ แล้วถ่วงน้ำหนักให้รวม 50
--
-- ⚠️ `seq` = "เลขข้อที่พิมพ์บนเอกสาร" ใช้แสดงผลเท่านั้น **ห้ามใช้เป็นคีย์**
--    เอกสารต้นฉบับพิมพ์เลขซ้ำจริง 1 จุด: หน่วยงาน `Production` มีข้อ "6" สองแถว
--    (Cost Reduction · Day Sales of Inventory) ⇒ คีย์เรียงลำดับใช้ `sort_order` แทน
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists kpi_standard_items (
  id           uuid primary key default gen_random_uuid(),
  year         int  not null,
  std_unit     text not null,                 -- หน่วยงานมาตรฐานตามเอกสาร เช่น 'Production'
  seq          text not null,                 -- เลขข้อที่พิมพ์บนใบ ('1' · '11.1') — แสดงผลเท่านั้น
  sort_order   int  not null,                 -- ลำดับจริงในตาราง (คีย์เรียง · seq ซ้ำได้)
  perspective  text not null check (perspective in ('financial','customer','internal','learning')),
  topic        text not null,
  formula_text text,
  requirement  text check (requirement in ('fixed','choice')),   -- null = แถวหัวข้อแม่
  catalog_id   uuid references kpi_catalog(id) on delete set null,
  note         text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create unique index if not exists kpi_standard_items_uniq on kpi_standard_items (year, std_unit, sort_order);
create index if not exists kpi_standard_items_unit_idx on kpi_standard_items (year, std_unit);
create index if not exists kpi_standard_items_topic_idx on kpi_standard_items (topic);

drop trigger if exists trg_kpi_standard_items_updated on kpi_standard_items;
create trigger trg_kpi_standard_items_updated before update on kpi_standard_items
  for each row execute function fn_set_updated_at();

alter table kpi_standard_items enable row level security;
-- อ่านได้ทุกคนที่ล็อกอิน (เป็นเอกสารอ้างอิง) · เขียนเฉพาะคนที่มีสิทธิ์ปุ่มตั้งค่า KPI บนจอ
drop policy if exists kpi_standard_items_read  on kpi_standard_items;
drop policy if exists kpi_standard_items_write on kpi_standard_items;
create policy kpi_standard_items_read  on kpi_standard_items for select using (true);
create policy kpi_standard_items_write on kpi_standard_items for all
  using (has_perm('kpi:manage')) with check (has_perm('kpi:manage'));

-- จำว่านิยาม KPI แถวนี้ถูกสร้างจาก "หน่วยงานมาตรฐาน" ไหน (ใช้ตอน sync เติมข้อ fixed ที่ขาด)
alter table kpi_definitions add column if not exists std_unit text;

delete from kpi_standard_items where year = 2026;
insert into kpi_standard_items (year, std_unit, seq, sort_order, perspective, topic, formula_text, requirement) values
  (2026, 'Head of SPG', '1', 1, 'financial', 'Total Sales', 'Sales From Product +Trading Goods +Tooling', 'fixed'),
  (2026, 'Head of SPG', '2', 2, 'financial', 'EBIT', '(EBIT value/Total Sales) x 100', 'fixed'),
  (2026, 'Head of SPG', '3', 3, 'customer', 'Customer Satisfaction (Q&D)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Head of SPG', '4', 4, 'customer', 'New Business or New Model (If any)', 'Sales of New Business or Sales of New Model', 'choice'),
  (2026, 'Head of SPG', '5', 5, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Head of SPG', '6', 6, 'internal', 'Overall Cost Improvement (100P)', '(Actual 100P/ Sales from product) X 100', 'fixed'),
  (2026, 'Head of SPG', '7', 7, 'internal', 'Cost Reduction', 'Reduce X% from last year or Value', 'fixed'),
  (2026, 'Head of SPG', '8', 8, 'internal', 'Day Sales of Inventory (DSI)', '(Stock value end of month/COGS) x Day', 'fixed'),
  (2026, 'Head of SPG', '9', 9, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'Head of SPG', '10', 10, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Head of SPG', '11', 11, 'learning', 'Engagement Survey', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Head of SPG', '12', 12, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Head of SPG', '12.1', 13, 'learning', 'QCC', '*Refer to activity announcement', 'fixed'),
  (2026, 'Head of SPG', '12.2', 14, 'learning', 'Engineering Day', '*Refer to activity announcement', 'fixed'),
  (2026, 'GM Plant', '1', 1, 'financial', 'Total Sales', 'Sales From Product +Trading Goods +Tooling', 'fixed'),
  (2026, 'GM Plant', '2', 2, 'financial', 'EBIT', '(EBIT value/Total Sales) x 100', 'fixed'),
  (2026, 'GM Plant', '3', 3, 'customer', 'Customer Satisfaction (Q&D)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'GM Plant', '4', 4, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'GM Plant', '5', 5, 'internal', 'Overall Cost Improvement (100P)', '(Actual 100P/ Sales from product) X 100', 'fixed'),
  (2026, 'GM Plant', '6', 6, 'internal', 'Cost Reduction', 'Reduce X% from last year or Value', 'fixed'),
  (2026, 'GM Plant', '7', 7, 'internal', 'Day Sales of Inventory (DSI)', '(Stock value end of month/COGS) x Day', 'fixed'),
  (2026, 'GM Plant', '8', 8, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'GM Plant', '9', 9, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'GM Plant', '10', 10, 'learning', 'Engagement Survey', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'GM Plant', '11', 11, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'GM Plant', '11.1', 12, 'learning', 'QCC', '*Refer to activity announcement', 'fixed'),
  (2026, 'GM Plant', '11.2', 13, 'learning', 'Engineering Day', '*Refer to activity announcement', 'fixed'),
  (2026, 'GM Plant (Tooling)', '1', 1, 'financial', 'Total Sales', 'Sales From Product +Trading Goods +Tooling', 'fixed'),
  (2026, 'GM Plant (Tooling)', '2', 2, 'financial', 'EBIT', '(EBIT value/Total Sales) x 100', 'fixed'),
  (2026, 'GM Plant (Tooling)', '3', 3, 'customer', 'Customer Satisfaction (Q&D)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'GM Plant (Tooling)', '4', 4, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'GM Plant (Tooling)', '5', 5, 'internal', 'Overall Cost Improvement (100P)', '(Actual 100P/ Sales from product) X 100', 'choice'),
  (2026, 'GM Plant (Tooling)', '6', 6, 'internal', 'Cost Reduction', 'Reduce X% from last year or Value', 'choice'),
  (2026, 'GM Plant (Tooling)', '7', 7, 'internal', 'First try out quality', '(1st Trial of Inspected data part ≥85% / Total 1st Trial of Inspected data part) x 100', 'fixed'),
  (2026, 'GM Plant (Tooling)', '8', 8, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'GM Plant (Tooling)', '9', 9, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'GM Plant (Tooling)', '10', 10, 'learning', 'Engagement Survey', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'GM Plant (Tooling)', '11', 11, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'GM Plant (Tooling)', '11.1', 12, 'learning', 'QCC', '*Refer to activity announcement', 'fixed'),
  (2026, 'GM Plant (Tooling)', '11.2', 13, 'learning', 'Engineering Day', '*Refer to activity announcement', 'choice'),
  (2026, 'Production', '1', 1, 'financial', 'Raw Material Control', '(Raw Material/Sales from product) x 100', 'fixed'),
  (2026, 'Production', '2', 2, 'financial', 'Direct Labour & Overhead Expenses', '[(DL+OH)/Sale from product] x 100', 'fixed'),
  (2026, 'Production', '3', 3, 'customer', 'Customer Satisfaction (Q&D)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Production', '4', 4, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Production', '5', 5, 'internal', 'Overall Cost Improvement (100P)', '(Actual 100P/ Sales from product) X 100', 'choice'),
  (2026, 'Production', '6', 6, 'internal', 'Cost Reduction', 'Reduce X% from last year or Value', 'choice'),
  (2026, 'Production', '6', 7, 'internal', 'Day Sales of Inventory (DSI)', '(Stock value end of month/COGS) x Day', 'fixed'),
  (2026, 'Production', '7', 8, 'internal', 'Internal Quality Rate', '(Defect/Total Production) x 1,000,000', 'fixed'),
  (2026, 'Production', '8', 9, 'internal', 'OEE', '% OEE = A x P x Q', 'fixed'),
  (2026, 'Production', '9', 10, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'Production', '10', 11, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Production', '11', 12, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Production', '11.1', 13, 'learning', 'QCC', '*Refer to activity announcement', 'fixed'),
  (2026, 'Production', '11.2', 14, 'learning', 'Engineering Day', '*Refer to activity announcement', 'fixed'),
  (2026, 'Engineering', '1', 1, 'financial', 'Direct Labour & Overhead Expenses', '[(DL+OH)/Sale from product] x 100', 'fixed'),
  (2026, 'Engineering', '2', 2, 'financial', 'Tooling payment on time (Receive from Customer)', '(Actual/Plan) x 100', 'choice'),
  (2026, 'Engineering', '3', 3, 'customer', 'Customer Satisfaction (Q&D)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Engineering', '4', 4, 'customer', 'Project Development on time', '[(Total part/part delivery on plan)/(Total part/part delivery)] x100', 'choice'),
  (2026, 'Engineering', '5', 5, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Engineering', '6', 6, 'internal', 'Overall Cost Improvement (100P)', '(Actual 100P/ Sales from product) X 100', 'choice'),
  (2026, 'Engineering', '7', 7, 'internal', 'Cost Reduction', 'Reduce X% from last year or Value', 'choice'),
  (2026, 'Engineering', '8', 8, 'internal', 'BOM and Routing on time as ECN', '(Actual correct BOM item/All BOM items) x 100', 'fixed'),
  (2026, 'Engineering', '9', 9, 'internal', 'Run@rate on target', '(Item on target/Total Item) x 100', 'choice'),
  (2026, 'Engineering', '10', 10, 'internal', 'BOM and Routing accruracy', '(Actual correct BOM item/All BOM items) x 100', 'fixed'),
  (2026, 'Engineering', '11', 11, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'Engineering', '12', 12, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Engineering', '13', 13, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Engineering', '13.1', 14, 'learning', 'QCC', '*Refer to activity announcement', 'fixed'),
  (2026, 'Engineering', '13.2', 15, 'learning', 'Engineering Day', '*Refer to activity announcement', 'fixed'),
  (2026, 'QA', '1', 1, 'financial', 'Direct Labour & Overhead Expenses', '[(DL+OH)/Sale from product] x 100', 'fixed'),
  (2026, 'QA', '2', 2, 'customer', 'Customer Satisfaction (Q&D)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'QA', '3', 3, 'customer', 'Customer Claim', '(Total Defect/Total Delivery) x 1,000,000', 'fixed'),
  (2026, 'QA', '4', 4, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'QA', '5', 5, 'internal', 'Incoming Quality Rate', '(Total Defect From Production or WH / Total Purchase Quantity) x 1,000,000', 'fixed'),
  (2026, 'QA', '6', 6, 'internal', 'Overall Cost Improvement (100P)', '[(Actual 100P)/Sale from product] x 100', 'choice'),
  (2026, 'QA', '7', 7, 'internal', 'Cost Reduction', 'Reduce X% from last year or Value', 'choice'),
  (2026, 'QA', '8', 8, 'internal', 'New Model Quality Rate', '(Total defect/Total production) x 1,000,000', 'choice'),
  (2026, 'QA', '9', 9, 'internal', 'Warranty claim', '0 Case', 'fixed'),
  (2026, 'QA', '10', 10, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'QA', '11', 11, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'QA', '12', 12, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'QA', '12.1', 13, 'learning', 'QCC', '*Refer to activity announcement', 'fixed'),
  (2026, 'QA', '12.2', 14, 'learning', 'Engineering Day', '*Refer to activity announcement', 'fixed'),
  (2026, 'Logistic & Sales', '1', 1, 'financial', 'Direct Labour & Overhead Expenses', '[(DL+OH)/Sale from product] x 100', 'choice'),
  (2026, 'Logistic & Sales', '2', 2, 'financial', 'Direct Labour & SG&A Expenses (หมวด 7)', '[(DL+SG&A)/Total Sale)] x100', 'choice'),
  (2026, 'Logistic & Sales', '3', 3, 'customer', 'Customer Satisfaction (Q&D)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Logistic & Sales', '4', 4, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Logistic & Sales', '5', 5, 'internal', 'Control Cancelled Bill', '(Cancelled Invoice/All Invoice) x 100', 'choice'),
  (2026, 'Logistic & Sales', '6', 6, 'internal', 'Cost Reduction', 'Reduce X% from last year or Value', 'choice'),
  (2026, 'Logistic & Sales', '7', 7, 'internal', 'Import Forecast & Order data into the SAP', '(Number of item passed/All item) x 100', 'choice'),
  (2026, 'Logistic & Sales', '8', 8, 'internal', 'Premium Freight', 'No costs from errors GL 64213120', 'choice'),
  (2026, 'Logistic & Sales', '9', 9, 'internal', 'Stock Accuracy', '(Stock actual count/SAP stock) x 100', 'choice'),
  (2026, 'Logistic & Sales', '10', 10, 'internal', 'Day Sales of Inventory (DSI)', '(Stock value end of month/COGS) x Day', 'choice'),
  (2026, 'Logistic & Sales', '11', 11, 'internal', 'Control supply production no stop', 'Number of interruptions', 'choice'),
  (2026, 'Logistic & Sales', '12', 12, 'internal', 'Control Long&Dead Stock', '[(Long+Dead stock end of month)/COGS)] x Day', 'choice'),
  (2026, 'Logistic & Sales', '13', 13, 'internal', 'Delivery on time', '(Actual Delivery/Total Plan Parts) x 100', 'choice'),
  (2026, 'Logistic & Sales', '14', 14, 'internal', 'Supplier delivery on time', '(Actual Delivery/Total Plan Parts) x 100', 'choice'),
  (2026, 'Logistic & Sales', '15', 15, 'internal', 'Miss delivery control', '(Number of miss/Total Lot in time PD) x 100', 'choice'),
  (2026, 'Logistic & Sales', '16', 16, 'internal', 'Control problems rack FG', 'Number of customer feedback', 'choice'),
  (2026, 'Logistic & Sales', '17', 17, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'Logistic & Sales', '18', 18, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Logistic & Sales', '19', 19, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Logistic & Sales', '19.1', 20, 'learning', 'QCC', '*Refer to activity announcement', 'fixed'),
  (2026, 'Logistic & Sales', '19.2', 21, 'learning', 'Engineering Day', '*Refer to activity announcement', 'choice'),
  (2026, 'Maintenance', '1', 1, 'financial', 'Direct Labour & Overhead Expenses', '[(DL+OH)/Sale from product] x 100', 'fixed'),
  (2026, 'Maintenance', '2', 2, 'customer', 'Internal Satisfaction', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Maintenance', '3', 3, 'customer', 'MO Closed on target', '(MO Closed on target/Total MO) x 100', 'fixed'),
  (2026, 'Maintenance', '4', 4, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Maintenance', '5', 5, 'internal', 'Machine Break Down', '(No. of hours the machine has been stopped / No. of hours the machine can work normally) x 100', 'fixed'),
  (2026, 'Maintenance', '6', 6, 'internal', 'Mean Time Between to Failure (MTBF)', '[(730 x Number of machines) - Total breakdown times)] / Number of machines', 'fixed'),
  (2026, 'Maintenance', '7', 7, 'internal', 'Mean Time To repair (MTTR)', 'Total hours of breakdown /Total frequency times', 'fixed'),
  (2026, 'Maintenance', '8', 8, 'internal', 'Cost Reduction (MTN)', 'CR value from improvement project', 'fixed'),
  (2026, 'Maintenance', '9', 9, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'Maintenance', '10', 10, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Maintenance', '11', 11, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Maintenance', '11.1', 12, 'learning', 'QCC', '*Refer to activity announcement', 'fixed'),
  (2026, 'Maintenance', '11.2', 13, 'learning', 'Engineering Day', '*Refer to activity announcement', 'choice'),
  (2026, 'Tooling', '1', 1, 'financial', 'Raw Material Control', '(Raw Material/Sales from product) x 100', 'fixed'),
  (2026, 'Tooling', '2', 2, 'financial', 'Direct Labour & Overhead Expenses', '[(DL+OH) / Sale from product] x 100', 'fixed'),
  (2026, 'Tooling', '3', 3, 'customer', 'Customer Satisfaction (Q&D)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Tooling', '4', 4, 'customer', 'Project Development on time', '[(Total part/Tooling delivery on plan) / (Total part/Tooling delivery)] x100', 'choice'),
  (2026, 'Tooling', '5', 5, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Tooling', '6', 6, 'internal', 'Overall Cost Improvement (100P)', '(Actual 100P/Sale from Product) x 100', 'fixed'),
  (2026, 'Tooling', '7', 7, 'internal', 'Control the quality of Die Design 100% efficiency', '(100% Qualified standard Die Design / Total Die Design) x 100', 'choice'),
  (2026, 'Tooling', '8', 8, 'internal', 'Control the quality of parts >85%', '( ≥85% First try out Checked Insp.data Part / Total First try out Checked Insp.data Part) x 100', 'choice'),
  (2026, 'Tooling', '9', 9, 'internal', 'Control the surface quality of machining ≥95%', '(≥ 95% Qualified Machining Die /Total Scanned Die) x 100', 'choice'),
  (2026, 'Tooling', '10', 10, 'internal', 'Static inspection quality ≥85%', '(≥85% Qualified Static Die / Total First try out Die) x 100', 'choice'),
  (2026, 'Tooling', '11', 11, 'internal', 'Control the quality of simulation parts 100%', '(100% Qualified Simulation Parts / Total Simulation Parts) x 100', 'choice'),
  (2026, 'Tooling', '12', 12, 'internal', 'Control the quality of parts (Off Tool) >95%', '(<3 times Off Tool Trial of ≥95% Qualified Part / Total Off Tool Trial) x 100', 'choice'),
  (2026, 'Tooling', '13', 13, 'internal', 'Control time for machining', '(Finished Machining Die as DMF / Total Die) x 100', 'choice'),
  (2026, 'Tooling', '14', 14, 'internal', 'Mold quality control must pass Die Spotting ≥95%', '(≥ 95% Qualified Off Tool Die spotting / Total Off Tool Die spotting) x 100', 'choice'),
  (2026, 'Tooling', '15', 15, 'internal', 'Control of part from part first try out', '(≥85% Parts Surface/All Parts) x 100', 'choice'),
  (2026, 'Tooling', '16', 16, 'internal', 'Reduce re-work', '[(Special Cost apart from Standard cost x Total defect) / Total production] x 100', 'choice'),
  (2026, 'Tooling', '17', 17, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'Tooling', '18', 18, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Tooling', '19', 19, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Tooling', '19.1', 20, 'learning', 'QCC', '*Refer to activity announcement', 'fixed'),
  (2026, 'Tooling', '19.2', 21, 'learning', 'Engineering Day', '*Refer to activity announcement', 'fixed'),
  (2026, 'Marketing', '1', 1, 'financial', 'Total Sales', 'Sales From Product +Trading Goods +Tooling', 'fixed'),
  (2026, 'Marketing', '1.1', 2, 'financial', 'Production Steel', 'Sales From Product +Trading Goods +Tooling', 'choice'),
  (2026, 'Marketing', '1.2', 3, 'financial', 'Production Plastic', 'Sales From Product +Trading Goods +Tooling', 'choice'),
  (2026, 'Marketing', '2', 4, 'financial', 'Budgeting', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'Marketing', '3', 5, 'financial', 'Tooling payment on time (Receive from Customer)', '(Actual/Plan) x 100', 'choice'),
  (2026, 'Marketing', '4', 6, 'customer', 'Customer Satisfaction (Q&D)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Marketing', '5', 7, 'customer', 'Customer Contract values in projection', 'Actual total contract values VS plan', 'fixed'),
  (2026, 'Marketing', '5.1', 8, 'customer', 'Production Steel', 'Actual total contract values VS plan', 'choice'),
  (2026, 'Marketing', '5.2', 9, 'customer', 'Production Plastic', 'Actual total contract values VS plan', 'choice'),
  (2026, 'Marketing', '6', 10, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Marketing', '7', 11, 'internal', 'Cost Reduction', 'Improvement Activity or Amount', 'choice'),
  (2026, 'Marketing', '8', 12, 'internal', 'Countermeasure', 'Improvement Activity Amount', 'choice'),
  (2026, 'Marketing', '9', 13, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Marketing', '10', 14, 'learning', 'Engagement Survey *GM only', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Marketing', '11', 15, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Marketing', '11.1', 16, 'learning', 'QCC', '*Refer to activity announcement', 'choice'),
  (2026, 'Marketing', '11.2', 17, 'learning', 'Kaizen', '*Refer to activity announcement', 'choice'),
  (2026, 'Marketing', '11.3', 18, 'learning', 'Environment', '*Refer to activity announcement', 'choice'),
  (2026, 'Marketing', '11.4', 19, 'learning', 'E-Day', '*Refer to activity announcement', 'choice'),
  (2026, 'RDPP', '1', 1, 'financial', 'Budgeting', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'RDPP', '2', 2, 'customer', 'Internal Satisfaction', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'RDPP', '3', 3, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'RDPP', '4', 4, 'internal', 'Cost Reduction or VAVE', 'Cost Reduction success', 'fixed'),
  (2026, 'RDPP', '5', 5, 'internal', 'Product design patent registration', 'Number of patent registration success', 'fixed'),
  (2026, 'RDPP', '6', 6, 'internal', 'Improvement quality or productivity of TSG product', 'Number of product success', 'fixed'),
  (2026, 'RDPP', '7', 7, 'internal', 'Benchmarking report', 'Make benchmarking or VE idea report', 'fixed'),
  (2026, 'RDPP', '8', 8, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'RDPP', '9', 9, 'learning', 'Engagement Survey *GM only', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'RDPP', '10', 10, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'RDPP', '10.1', 11, 'learning', 'QCC', '*Refer to activity announcement', 'choice'),
  (2026, 'RDPP', '10.2', 12, 'learning', 'Kaizen', '*Refer to activity announcement', 'choice'),
  (2026, 'RDPP', '10.3', 13, 'learning', 'Environment', '*Refer to activity announcement', 'choice'),
  (2026, 'RDPP', '10.4', 14, 'learning', 'E-Day', '*Refer to activity announcement', 'choice'),
  (2026, 'CSC', '1', 1, 'financial', 'Budgeting', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'CSC', '2', 2, 'customer', 'Internal Satisfaction', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'CSC', '3', 3, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'CSC', '4', 4, 'internal', 'Cost Reduction or VAVE idea (CSC)', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'CSC', '5', 5, 'internal', 'Error control in process planning', '[(Number of bidding processes-Actual process)/Actual process] x 100', 'fixed'),
  (2026, 'CSC', '6', 6, 'internal', 'Error in blank size process', '[(Number of blank size-Actual blank size)/Actual blank size] x 100', 'fixed'),
  (2026, 'CSC', '7', 7, 'internal', 'Knowledge sharing topic', 'Create knowledge sharing', 'fixed'),
  (2026, 'CSC', '8', 8, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'CSC', '9', 9, 'learning', 'Engagement Survey *GM only', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'CSC', '10', 10, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'CSC', '10.1', 11, 'learning', 'QCC', '*Refer to activity announcement', 'choice'),
  (2026, 'CSC', '10.2', 12, 'learning', 'Kaizen', '*Refer to activity announcement', 'choice'),
  (2026, 'CSC', '10.3', 13, 'learning', 'Environment', '*Refer to activity announcement', 'choice'),
  (2026, 'CSC', '10.4', 14, 'learning', 'E-Day', '*Refer to activity announcement', 'choice'),
  (2026, 'Accounting', '1', 1, 'financial', 'EBIT', '(EBIT value/Total Sales) x 100', 'fixed'),
  (2026, 'Accounting', '2', 2, 'financial', 'Budgeting', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'Accounting', '3', 3, 'customer', 'Internal Satisfaction', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Accounting', '4', 4, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Accounting', '5', 5, 'internal', 'Report on time', 'Sent report to SPG/Region with in 15 Days, Send to plant with in 10 Days', 'fixed'),
  (2026, 'Accounting', '6', 6, 'internal', 'Transfer Pricing Report', '1 Document', 'fixed'),
  (2026, 'Accounting', '7', 7, 'internal', 'AR Aging', '(AR Overdue/AR Overdue last year) x 100', 'fixed'),
  (2026, 'Accounting', '8', 8, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Accounting', '9', 9, 'learning', 'Engagement Survey *GM only', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Accounting', '10', 10, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Accounting', '10.1', 11, 'learning', 'QCC', '*Refer to activity announcement', 'choice'),
  (2026, 'Accounting', '10.2', 12, 'learning', 'Kaizen', '*Refer to activity announcement', 'choice'),
  (2026, 'Accounting', '10.3', 13, 'learning', 'Environment', '*Refer to activity announcement', 'choice'),
  (2026, 'Purchase', '1', 1, 'financial', 'EBIT', '(EBIT value/Total Sales) x 100', 'fixed'),
  (2026, 'Purchase', '2', 2, 'financial', 'Budgeting', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'Purchase', '3', 3, 'customer', 'Internal Satisfaction', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Purchase', '4', 4, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Purchase', '5', 5, 'internal', 'Cost reduction (PUR)', '[(Reduce amount x Volumn)/All Purchase amount] x 100', 'fixed'),
  (2026, 'Purchase', '6', 6, 'internal', 'Cost control', '(Number of item increased prices/All item) x 100', 'fixed'),
  (2026, 'Purchase', '7', 7, 'internal', 'Vendor Evaluation', '(Actual score/Total score) x 100', 'fixed'),
  (2026, 'Purchase', '8', 8, 'internal', 'PR Pending', '(PR Pending/All PR) x 100', 'fixed'),
  (2026, 'Purchase', '9', 9, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Purchase', '10', 10, 'learning', 'Engagement Survey *GM only', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Purchase', '11', 11, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Purchase', '11.1', 12, 'learning', 'QCC', '*Refer to activity announcement', 'choice'),
  (2026, 'Purchase', '11.2', 13, 'learning', 'Kaizen', '*Refer to activity announcement', 'choice'),
  (2026, 'Purchase', '11.3', 14, 'learning', 'Environment', '*Refer to activity announcement', 'choice'),
  (2026, 'Purchase', '11.4', 15, 'learning', 'E-Day', '*Refer to activity announcement', 'choice'),
  (2026, 'HRM', '1', 1, 'financial', 'Budgeting', null, null),
  (2026, 'HRM', '1.1', 2, 'financial', 'Budgeting (HRM)', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'HRM', '1.2', 3, 'financial', 'Budgeting (HRM Center)', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'HRM', '2', 4, 'customer', 'Service Level Agreement', 'Achieve number of item', 'fixed'),
  (2026, 'HRM', '2.1', 5, 'customer', 'Employee training', '(Number of employee training/Number of employees confirmed) x 100', null),
  (2026, 'HRM', '2.2', 6, 'customer', 'Recruitment employees', 'Number of days to recruit employees', null),
  (2026, 'HRM', '2.3', 7, 'customer', 'Annual health check', '(Number of annual health check employees/All employee) x 100', null),
  (2026, 'HRM', '2.4', 8, 'customer', 'General Affair satisfaction', '(Actual Score/Total Score) x 100', null),
  (2026, 'HRM', '2.5', 9, 'customer', 'Outstanding Establishment Award in Labor Relations', 'Received the Outstanding Establishment Award in Labor Relations', null),
  (2026, 'HRM', '2.6', 10, 'customer', 'Turnover rate (Working period > 3 years)', '(Number of employees resigned/Average employee) x 100', null),
  (2026, 'HRM', '3', 11, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'HRM', '4', 12, 'internal', 'Cost Reduction (HRM)', '(HR Center budgeting plan x 95%) x 2%', 'fixed'),
  (2026, 'HRM', '5', 13, 'internal', 'Number of issue from Audit', 'Number of issue', 'fixed'),
  (2026, 'HRM', '6', 14, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'HRM', '7', 15, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'HRM', '8', 16, 'learning', 'Engagement Survey', null, null),
  (2026, 'HRM', '8.1', 17, 'learning', 'Engagement Survey (Score)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'HRM', '8.2', 18, 'learning', 'Engagement Survey (Participation)', '(Number of employee survey/Total employee) x 100', 'fixed'),
  (2026, 'HRM', '9', 19, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'HRM', '9.1', 20, 'learning', 'QCC', '*Refer to activity announcement', 'choice'),
  (2026, 'HRM', '9.2', 21, 'learning', 'Kaizen', '*Refer to activity announcement', 'choice'),
  (2026, 'HRM', '9.3', 22, 'learning', 'Environment', '*Refer to activity announcement', 'choice'),
  (2026, 'CIC', '1', 1, 'financial', 'Budgeting', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'CIC', '2', 2, 'customer', 'Service Level Agreement', '(Number of passed item/All item) x 100', 'fixed'),
  (2026, 'CIC', '2.1', 3, 'customer', 'Recording tax invoices into SAP system', '(Number of passed Tax invoice/All Tax invoice) x 100', 'choice'),
  (2026, 'CIC', '2.2', 4, 'customer', 'Control Overdue CIC Control documents', '(Number of Pending CIC Control/All CIC Control) x 100', 'fixed'),
  (2026, 'CIC', '2.3', 5, 'customer', 'Reporting a problem (2.3.1 GR report · 2.3.2 Scrap report · 2.3.3 Job Acceptance report (Project, Tooling))', 'Send report to plant within 3 days', 'choice'),
  (2026, 'CIC', '3', 6, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'CIC', '4', 7, 'internal', 'GR Slip accruacy compare Tax Invoice', '(Number of Corrected GR Slip/Total Tax Invoice) x 100', 'fixed'),
  (2026, 'CIC', '5', 8, 'internal', 'Submit GR & Invoice to Accounting', 'Send GR report & Invoice to ACC within 1 day', 'fixed'),
  (2026, 'CIC', '6', 9, 'internal', 'Attached file into CIC Control system', '(Number of passed item /All item) x 100 — Attach data within 2 days of next month', 'fixed'),
  (2026, 'CIC', '7', 10, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'CIC', '8', 11, 'learning', 'Engagement Survey', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'CIC', '9', 12, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'CIC', '9.1', 13, 'learning', 'QCC', '*Refer to activity announcement', 'choice'),
  (2026, 'CIC', '9.2', 14, 'learning', 'Kaizen', '*Refer to activity announcement', 'choice'),
  (2026, 'CIC', '9.3', 15, 'learning', 'Environment', '*Refer to activity announcement', 'choice'),
  (2026, 'QSM', '1', 1, 'financial', 'Budgeting', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'QSM', '2', 2, 'customer', 'Internal satisfaction', '(Actual Score / Total Score) x100', 'fixed'),
  (2026, 'QSM', '3', 3, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'QSM', '4', 4, 'internal', 'Close NC issues on time', '(Number of issue on time/All issue) x 100', 'fixed'),
  (2026, 'QSM', '5', 5, 'internal', 'Internal audit activity', '[(Actual activity/Plan activity)x 80%]+[(Actual NC closed score / Plan NC closed score) x 20%]', 'fixed'),
  (2026, 'QSM', '6', 6, 'internal', 'Safety activity', 'Result Score for Safety activity', 'fixed'),
  (2026, 'QSM', '7', 7, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'QSM', '8', 8, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'QSM', '8.1', 9, 'learning', 'QCC', '*Refer to activity announcement', 'choice'),
  (2026, 'QSM', '8.2', 10, 'learning', 'Kaizen', '*Refer to activity announcement', 'choice'),
  (2026, 'QSM', '8.3', 11, 'learning', 'Environment', '*Refer to activity announcement', 'choice'),
  (2026, 'IT-TSA', '1', 1, 'financial', 'Total Sales', 'Sales From Product +Trading Goods +Tooling', 'fixed'),
  (2026, 'IT-TSA', '2', 2, 'financial', 'EBIT', '(EBIT value/Total Sales) x 100', 'fixed'),
  (2026, 'IT-TSA', '3', 3, 'financial', 'Budgeting', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'IT-TSA', '4', 4, 'customer', 'Service Level Agreement (IT)', '(Number of company passed/All company) x 100', 'fixed'),
  (2026, 'IT-TSA', '4.1', 5, 'customer', 'SAP', '(Number of item passed/All item) x 100', null),
  (2026, 'IT-TSA', '4.2', 6, 'customer', 'Non SAP', '(Number of item passed/All item) x 100', null),
  (2026, 'IT-TSA', '4.3', 7, 'customer', 'Infrastructure', '(Number of item passed/All item) x 100', null),
  (2026, 'IT-TSA', '5', 8, 'customer', 'Overseas one stop service', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'IT-TSA', '6', 9, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'IT-TSA', '7', 10, 'internal', '100P (TSA)', null, null),
  (2026, 'IT-TSA', '7.1', 11, 'internal', 'Improvement Project', 'Present in CIW', 'fixed'),
  (2026, 'IT-TSA', '7.2', 12, 'internal', 'Reduce costs', '(Reduce costs to TSA or TSG/Sale from service TSA) x 100', 'fixed'),
  (2026, 'IT-TSA', '8', 13, 'internal', '100P (TS Group)', 'Number of plant passed', 'fixed'),
  (2026, 'IT-TSA', '9', 14, 'internal', 'Working Process', '(Number of Passed employee working process/Total employee) x 100', 'fixed'),
  (2026, 'IT-TSA', '10', 15, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'IT-TSA', '11', 16, 'learning', 'Engagement Survey', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'IT-TSA', '12', 17, 'learning', 'Knowledge Management (KM)', 'Number of KM', 'fixed'),
  (2026, 'IT-TSA', '13', 18, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'IT-TSA', '13.1', 19, 'learning', 'QCC', '*Refer to activity announcement', 'choice'),
  (2026, 'IT-TSA', '13.2', 20, 'learning', 'Environment', '*Refer to activity announcement', 'choice'),
  (2026, 'IT-TSA', '13.3', 21, 'learning', 'Energy Saving', '*Refer to activity announcement', 'choice'),
  (2026, 'Purchase-TSA', '1', 1, 'financial', 'Total Sales', 'Sales From Product +Trading Goods +Tooling', 'fixed'),
  (2026, 'Purchase-TSA', '2', 2, 'financial', 'EBIT', '(EBIT value/Total Sales) x 100', 'fixed'),
  (2026, 'Purchase-TSA', '3', 3, 'financial', 'Budgeting', '(Actual/Plan) x 100', 'fixed'),
  (2026, 'Purchase-TSA', '4', 4, 'customer', 'Service Level Agreement (Purchase)', '(Number of item passed/All item) x 100', 'fixed'),
  (2026, 'Purchase-TSA', '4.1', 5, 'customer', 'Able to buy the investment asset and improvement project of all SPG as on schedule', 'PO must create within 30 days (data from SAP)', null),
  (2026, 'Purchase-TSA', '4.2', 6, 'customer', 'Able to buy the general and usage of TSA', 'PO must create within 15 days (data from SAP)', null),
  (2026, 'Purchase-TSA', '4.3', 7, 'customer', 'Manage imports from overseas till delivery within the due date', 'Number of shipment x 100', null),
  (2026, 'Purchase-TSA', '4.4', 8, 'customer', 'Manage exports overseas within the due date', 'Number of shipment x 100', null),
  (2026, 'Purchase-TSA', '4.5', 9, 'customer', 'Rules of Origin Verification & Certificate of Origin', 'Quantity of finished goods list that requests the certificate of origin x 100', null),
  (2026, 'Purchase-TSA', '4.6', 10, 'customer', 'Application for import permission of goods from overseas', 'Number of application has been received within the agreed-upon timeframe', null),
  (2026, 'Purchase-TSA', '5', 11, 'customer', 'Overseas one stop service', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Purchase-TSA', '6', 12, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Purchase-TSA', '7', 13, 'internal', '100P (TSA)', null, null),
  (2026, 'Purchase-TSA', '7.1', 14, 'internal', 'Improvement Project', 'Present in CIW', 'fixed'),
  (2026, 'Purchase-TSA', '7.2', 15, 'internal', 'Reduce costs', '(Reduce costs to TSA or TSG/Sale from service TSA) x 100', 'fixed'),
  (2026, 'Purchase-TSA', '8', 16, 'internal', '100P (TS Group)', 'Number of plant passed', 'fixed'),
  (2026, 'Purchase-TSA', '9', 17, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Purchase-TSA', '10', 18, 'learning', 'Engagement Survey', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Purchase-TSA', '11', 19, 'learning', 'Knowledge Management (KM)', 'Number of KM', 'fixed'),
  (2026, 'Purchase-TSA', '12', 20, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Purchase-TSA', '12.1', 21, 'learning', 'QCC', '*Refer to activity announcement', 'choice'),
  (2026, 'Purchase-TSA', '12.2', 22, 'learning', 'Environment', '*Refer to activity announcement', 'choice'),
  (2026, 'Purchase-TSA', '12.3', 23, 'learning', 'Energy Saving', '*Refer to activity announcement', 'choice'),
  (2026, 'Die Maintenance', '1', 1, 'financial', 'Direct Labour & Overhead Expenses', '[(DL+OH)/Sale from product] x 100', 'fixed'),
  (2026, 'Die Maintenance', '2', 2, 'customer', 'Customer Satisfaction (Q&D)', '(Actual Score/Total Score) x 100', 'fixed'),
  (2026, 'Die Maintenance', '3', 3, 'customer', 'Manage project to achieve & on time delivery to customer as target', '(No of time to delivery part on time & Quanlity / No of time to delivery part as customer plan) x 100', 'choice'),
  (2026, 'Die Maintenance', '4', 4, 'internal', 'Safety', '*Refer to safety announcement', 'fixed'),
  (2026, 'Die Maintenance', '5', 5, 'internal', 'Reduce interuption from mold problems', '100 - [(Actual this year/Actual in the past 2 year) x 100]', 'choice'),
  (2026, 'Die Maintenance', '6', 6, 'internal', 'Keep inventory no more than', '(Stock value end of month/Total Sales) x 100', 'choice'),
  (2026, 'Die Maintenance', '7', 7, 'internal', 'Part quality concern from Dies & Jig MTN', 'Actual concern customer from Dies & Jig MTN', 'choice'),
  (2026, 'Die Maintenance', '8', 8, 'internal', 'Reduce part rework from DIE & JIG tooling', '(Actual part rework/Total Production) X 100', 'choice'),
  (2026, 'Die Maintenance', '9', 9, 'learning', 'Annual Sale Per Head', 'Total Sales/Average manpower', 'fixed'),
  (2026, 'Die Maintenance', '10', 10, 'learning', 'TS Academy training', '(Number of Passed training employee/Total Employee) x 100', 'fixed'),
  (2026, 'Die Maintenance', '11', 11, 'learning', 'Activity', 'Number of Passed Activity', null),
  (2026, 'Die Maintenance', '11.1', 12, 'learning', 'QCC', '*Refer to activity announcement', 'fixed'),
  (2026, 'Die Maintenance', '11.2', 13, 'learning', 'Engineering Day', '*Refer to activity announcement', 'choice');

-- ─────────────────────────────────────────────────────────────────────────────
-- ⚠️ ยัง **ไม่ได้ seed** 4 หน่วยงานสำนักงานใหญ่ TSA: Accounting-TSA · HRM-TSA ·
--    Internal Audit-TSA · AOBM-TSA — ตารางต้นฉบับหน้า 16-18 มีข้อย่อยซ้อนหลายชั้น
--    (4.1-4.9) ที่ถอดออกมาแล้วนับ `Fixed`/`Choice` ไม่ตรงกับในไฟล์ PDF
--    ⇒ **ตั้งใจไม่ใส่ ดีกว่าใส่ผิด** (ESM เป็นระบบระดับโรงงาน ไม่ได้ให้บริการหน่วยงาน TSA พวกนี้)
--    ถ้าจะเพิ่มทีหลัง ต้องถอดมือแล้วตรวจยอด Fixed/Choice ให้ตรงกับ PDF ก่อนเสมอ
--
-- ⚠️ เกณฑ์ของ Safety / QCC / Engineering Day / Kaizen / Environment / Energy Saving
--    เอกสารเขียนแค่ `*Refer to safety announcement` และ `*Refer to activity announcement`
--    = อยู่ใน "ประกาศ" คนละฉบับที่ยังไม่มี (user แจ้ง 21/09: แล้วแต่ประธานกิจจะแจ้ง ค่อยใส่ทีหลัง)
-- ═══════════════════════════════════════════════════════════════════════════
-- ROLLBACK
--   alter table kpi_definitions drop column if exists std_unit;
--   drop table if exists kpi_standard_items;
-- ═══════════════════════════════════════════════════════════════════════════
