-- Poka-Yoke Check — ทะเบียนอุปกรณ์ error-proofing ต่อไลน์ + บันทึกทดสอบรายวัน/กะ (2026-07-23)
-- TPM daily poka-yoke verification: เอาชิ้น master NG มาลองว่าอุปกรณ์จับได้ไหม → ผ่าน/ไม่ผ่าน
-- แท็บที่ 3 ใน Daily Checker (/pokayoke) · Main project (authenticated + UI can() gating)

create table if not exists public.pokayoke_devices (
  id         bigint generated by default as identity primary key,
  line_name  text not null,
  code       text,               -- รหัสอุปกรณ์ (optional)
  name       text not null,      -- ชื่อ/หน้าที่ error-proofing
  station    text,               -- จุดงาน/ตำแหน่ง
  test_method text,              -- วิธีทดสอบ
  master_ref text,               -- ชิ้น master NG ที่ใช้ทดสอบ
  is_active  boolean not null default true,
  sort       int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists pokayoke_devices_line_idx on public.pokayoke_devices(line_name);

create table if not exists public.pokayoke_checks (
  id           bigint generated by default as identity primary key,
  device_id    bigint not null references public.pokayoke_devices(id) on delete cascade,
  check_date   date not null,
  shift        text not null,             -- day/night
  result       text not null,             -- pass/fail
  detected     boolean,                   -- อุปกรณ์จับชิ้น NG ได้ไหม (true=จับได้=ปกติ)
  note         text,
  checker_name text,
  checker_sig_url text,
  created_by   uuid,
  created_at   timestamptz not null default now(),
  unique(device_id, check_date, shift)
);
create index if not exists pokayoke_checks_date_idx on public.pokayoke_checks(check_date, shift);

alter table public.pokayoke_devices enable row level security;
alter table public.pokayoke_checks  enable row level security;
-- อ่าน/เขียนได้ทุก user ที่ login (UI คุมด้วย can('pokayoke','record'/'manage')) — pattern เดียวกับตาราง Main อื่น
do $$ begin
  create policy pokayoke_devices_all on public.pokayoke_devices for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy pokayoke_checks_all on public.pokayoke_checks for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- ── สิทธิ์ ──
-- page:/pokayoke = ทุก role (เหมือน page:/lpa) · pokayoke:record = admin/mgr/sv/leader · manage = admin/mgr/sv
insert into public.role_permissions (role, permission_key, allowed)
select r.role, 'page:/pokayoke', true from unnest(enum_range(null::user_role)) as r(role)
where not exists (select 1 from public.role_permissions rp where rp.role = r.role and rp.permission_key = 'page:/pokayoke');

insert into public.role_permissions (role, permission_key, allowed)
select r.role, k.key, true
from (values ('admin'::user_role),('manager'::user_role),('supervisor'::user_role),('leader'::user_role)) as r(role)
cross join (values ('pokayoke:record')) as k(key)
where not exists (select 1 from public.role_permissions rp where rp.role = r.role and rp.permission_key = k.key);

insert into public.role_permissions (role, permission_key, allowed)
select r.role, k.key, true
from (values ('admin'::user_role),('manager'::user_role),('supervisor'::user_role)) as r(role)
cross join (values ('pokayoke:manage')) as k(key)
where not exists (select 1 from public.role_permissions rp where rp.role = r.role and rp.permission_key = k.key);

-- catalog (แท็บสิทธิ์การทำงาน)
delete from public.permission_catalog where (resource, action) in (('pokayoke','record'), ('pokayoke','manage'));
insert into public.permission_catalog (resource, action, label, group_name, sort) values
  ('pokayoke', 'record', 'Poka-Yoke: บันทึกผลทดสอบรายวัน',        'ฝ่ายผลิต', 18),
  ('pokayoke', 'manage', 'Poka-Yoke: จัดการทะเบียนอุปกรณ์',       'ฝ่ายผลิต', 19);
